export const COMMON_MEDICINES = [
  "Amoxicillin", "Aspirin", "Azithromycin", "Albuterol", "Amlodipine", "Atorvastatin", "Acetaminophen", "Adderall", "Alprazolam", "Amitriptyline",
  "Bactrim", "Benazepril", "Budesonide", "Bupropion", "Buspirone", "Bystolic", "Baclofen", "Benzonatate",
  "Ciprofloxacin", "Cephalexin", "Citalopram", "Clonazepam", "Clopidogrel", "Carvedilol", "Cetirizine", "Cyclobenzaprine", "Cymbalta",
  "Doxycycline", "Duloxetine", "Diclofenac", "Dicyclomine", "Digoxin", "Diltiazem", "Diazepam", "Docusate",
  "Escitalopram", "Esomeprazole", "Estradiol", "Enalapril", "Ezetimibe", "Eliquis", "Erythromycin",
  "Fluoxetine", "Fluticasone", "Furosemide", "Famotidine", "Finasteride", "Fluconazole", "Folic Acid", "Flexeril",
  "Gabapentin", "Glipizide", "Glimepiride", "Glyburide", "Guaifenesin", "Guanfacine",
  "Hydrochlorothiazide", "Hydrocodone", "Hydroxyzine", "Hydralazine", "Humalog", "Humira",
  "Ibuprofen", "Insulin Glargine", "Isosorbide Mononitrate", "Indomethacin", "Irbesartan",
  "Januvia", "Jardiance", "Janumet",
  "Ketoconazole", "Ketorolac", "Keppra",
  "Levothyroxine", "Lisinopril", "Losartan", "Loratadine", "Lorazepam", "Lovastatin", "Levofloxacin", "Lantus", "Lamotrigine", "Lexapro",
  "Metformin", "Metoprolol", "Meloxicam", "Montelukast", "Mirtazapine", "Methotrexate", "Methylprednisolone", "Mupirocin", "Metronidazole",
  "Naproxen", "Nitrofurantoin", "Nortriptyline", "Novolog", "Nexium", "Nifedipine", "Norvasc",
  "Omeprazole", "Ondansetron", "Oxycodone", "Oxybutynin", "Olanzapine", "Ozempic",
  "Pantoprazole", "Prednisone", "Pravastatin", "Paroxetine", "Propranolol", "Promethazine", "Pregabalin", "Penicillin", "Phentermine",
  "Quetiapine", "Quinapril",
  "Rosuvastatin", "Ranitidine", "Risperidone", "Ropinirole", "Ramipril", "Rivaroxaban",
  "Sertraline", "Simvastatin", "Spironolactone", "Symbicort", "Sildenafil", "Sitagliptin", "Sulfamethoxazole",
  "Tamsulosin", "Tramadol", "Trazodone", "Topiramate", "Tizanidine", "Torsemide", "Tadalafil",
  "Valacyclovir", "Venlafaxine", "Valsartan", "Verapamil", "Vitamin D", "Victoza",
  "Warfarin", "Wellbutrin",
  "Xanax", "Xarelto",
  "Zolpidem", "Zyrtec", "Zoloft", "Zithromax", "Zetia"
];
